GAME_DATASET = [
    {"name": "League of Legends", "description": "A multiplayer online battle arena (MOBA) game developed by Riot Games, known for its competitive gameplay and large esports scene.", "revenue": 1700000000},
    {"name": "Honor of Kings / Arena of Valor", "description": "A MOBA game developed by Tencent, popular in China and later released internationally as Arena of Valor.", "revenue": 1300000000},
    {"name": "Monster Strike", "description": "A mobile physics-based game developed by Mixi, combining elements of role-playing and puzzle-solving.", "revenue": 1200000000},
    {"name": "Clash of Clans", "description": "A strategy game developed by Supercell, focusing on building and defending villages while engaging in clan wars.", "revenue": 1510000000},
    {"name": "Dungeon Fighter Online", "description": "A beat 'em up game developed by Nexon, featuring side-scrolling action and a variety of character classes.", "revenue": 1260000000},
    {"name": "Clash Royale", "description": "A real-time strategy game developed by Supercell, combining elements of tower defense and card games.", "revenue": 1060000000},
    {"name": "Crossfire", "description": "A first-person shooter game developed by Smilegate, known for its tactical gameplay and large player base in Asia.", "revenue": 1050000000},
    {"name": "Puzzle & Dragons", "description": "A puzzle role-playing game developed by GungHo Online Entertainment, featuring match-3 gameplay and monster collection.", "revenue": 900000000},
    {"name": "Pokémon Go", "description": "An augmented reality game developed by Niantic, allowing players to catch Pokémon in the real world using mobile devices.", "revenue": 950000000},
    {"name": "Game of War: Fire Age", "description": "A strategy game developed by Machine Zone, focusing on building empires and engaging in large-scale wars.", "revenue": 910000000},
    {"name": "World of Warcraft", "description": "A massively multiplayer online role-playing game (MMORPG) developed by Blizzard Entertainment, known for its expansive world and rich lore.", "revenue": 810000000},
    {"name": "FIFA 17", "description": "A sports simulation game developed by EA Sports, featuring realistic soccer gameplay and licensed teams.", "revenue": 800000000},
    {"name": "Final Fantasy XV", "description": "An action role-playing game developed by Square Enix, part of the long-running Final Fantasy series.", "revenue": 770000000},
    {"name": "Overwatch", "description": "A team-based first-person shooter developed by Blizzard Entertainment, known for its diverse cast of characters and strategic gameplay.", "revenue": 700000000},
    {"name": "Tom Clancy's The Division", "description": "An online-only third-person shooter game developed by Ubisoft, set in a post-apocalyptic New York City.", "revenue": 650000000},
    {"name": "Battlefield 1", "description": "A first-person shooter game developed by EA DICE, set during World War I, known for its large-scale battles and destructible environments.", "revenue": 600000000},
    {"name": "Madden NFL 17", "description": "An American football video game developed by EA Sports, featuring realistic gameplay and licensed NFL teams.", "revenue": 550000000},
    {"name": "NBA 2K17", "description": "A basketball simulation game developed by Visual Concepts, known for its realistic gameplay and detailed player models.", "revenue": 520000000},
    {"name": "Pokémon Sun and Moon", "description": "Role-playing games developed by Game Freak, introducing the Alola region and new Pokémon species.", "revenue": 500000000},
    {"name": "Super Mario Maker", "description": "A platform game developed by Nintendo, allowing players to create and share their own Mario levels.", "revenue": 450000000},
    {"name": "Call of Duty: Infinite Warfare", "description": "A first-person shooter game developed by Infinity Ward, featuring a futuristic setting and space combat.", "revenue": 400000000},
    {"name": "Pokémon Go Plus", "description": "A wearable device that enhances the Pokémon Go experience by providing notifications and tracking steps.", "revenue": 380000000},
    {"name": "Pokémon Sun and Moon Special Demo Version", "description": "A free demo version of Pokémon Sun and Moon, offering a preview of the full game.", "revenue": 350000000},
    {"name": "Super Mario Run", "description": "A mobile platformer game developed by Nintendo, featuring classic Mario gameplay with one-touch controls.", "revenue": 300000000},
    {"name": "Pokémon TCG Online", "description": "A digital version of the Pokémon Trading Card Game, allowing players to collect and battle with virtual cards.", "revenue": 280000000},
    {"name": "Pokémon Rumble World", "description": "A free-to-play action game developed by Nintendo, allowing players to capture toy Pokémon and battle through various stages.", "revenue": 250000000},
    {"name": "Hitman", "description": "A stealth-based action-adventure game developed by IO Interactive, featuring the infamous assassin Agent 47.", "revenue": 240000000},
    {"name": "Lara Croft: Guardian of Light", "description": "An action-adventure game developed by Crystal Dynamics, part of the Tomb Raider franchise.", "revenue": 230000000},
    {"name": "The Elder Scrolls Online", "description": "An MMORPG developed by ZeniMax Online Studios, set in the Elder Scrolls universe.", "revenue": 220000000},
    {"name": "Street Fighter V", "description": "A fighting game developed by Capcom, featuring the iconic characters from the Street Fighter franchise.", "revenue": 210000000},
    {"name": "Gears of War 4", "description": "A third-person shooter developed by The Coalition, continuing the Gears of War series with new characters and a new storyline.", "revenue": 200000000},
    {"name": "Dead Rising 4", "description": "A survival horror game developed by Capcom Vancouver, focusing on zombie combat and exploration.", "revenue": 190000000},
    {"name": "Watch Dogs 2", "description": "An action-adventure game developed by Ubisoft, featuring hacking and open-world gameplay set in a fictional San Francisco.", "revenue": 180000000},
    {"name": "The Witcher 3: Wild Hunt – Blood and Wine", "description": "The second major expansion for The Witcher 3, featuring a new story and area to explore.", "revenue": 170000000},
    {"name": "Total War: Warhammer", "description": "A strategy game developed by Creative Assembly, set in the Warhammer Fantasy universe.", "revenue": 160000000},
    {"name": "Dark Souls III", "description": "An action role-playing game developed by FromSoftware, known for its challenging gameplay and dark fantasy setting.", "revenue": 150000000}
]
